### ISSUE TITLE
Deep learning/image processing samples? 

### ISSUE THREAD

**Issue by tesar-tech** [XamlBrewer/UWP-MachineLearning-Sample#3]
Are there any plans to add image processing samples? 
Great start could be here: https://github.com/Tak-Au/Photo-Search (using onnx model) or in official ml.net samples ([image classification](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow) , [object detection](
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ObjectDetection_Onnx) )

**Comment by XamlBrewer** [comment]
As long as it sparks joy, I'll keep on adding samples. Image processing and deep learning are at this time just not priority 1.
