### ISSUE TITLE
Can't run the App

### ISSUE THREAD

**Issue by redcican** [XamlBrewer/UWP-MachineLearning-Sample#4]
Hi, I am trying to run the App. But it failed:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	XDG0062	Type Mvvm.ShellViewModel cannot be created in XAML. Building the project may help.	XamlBrewer.Uwp.MachineLearningSample	Shell.xaml	12	

```

**Comment by XamlBrewer** [comment]
Let's try to establish a list of requirements for running the app.
You need:
- A Visual Studio that is capable of creating UWP apps. (remark: Visual Studio Code is not sufficient)
- A Windows 10 box with the OS version 1809 or higher

If you have these, the app should run.

I also noticed a recent similar issue: https://developercommunity.visualstudio.com/content/problem/739100/xaml-cannot-find-my-viewmodel.html

**Comment by redcican** [comment]
@XamlBrewer I have Visual Studio Professional 2019 and Windows 10 1903 OS. 
But I still can not build your app successfully. If I rewrite your app by using WPF, is it possible?

**Comment by XamlBrewer** [comment]
Did you install the UWP Workload in Visual Studio? (Visual Studio Installer -> Modify)

![VsWorkloadForUwp](https://user-images.githubusercontent.com/9828352/65714316-2366c080-e09b-11e9-83d9-23c74e3eed59.png)

When rewriting for WPF you will need to start from scratch.

**Comment by redcican** [comment]
Yes I did. Actually after changing the Platform target to x64, the app works. Thank you very much! Do you have any plane to write blogs about ML.Net by using WPF?

**Comment by CESARDELATORRE** [comment]
Do you mean WPF or UWP?

**Comment by redcican** [comment]
I mean WPF.

**Comment by CESARDELATORRE** [comment]
Not sure about Blog Post, but you have a simple WPF sample using ML.NET here:

The scenario is about anomaly detection on spikes detection (Time series based).

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/AnomalyDetection-Sales

**Comment by XamlBrewer** [comment]
Since the app runs, I'm closing the issue.
